### ISSUE TITLE
Support multiple return values

### ISSUE THREAD

**Issue by onbjerg** [aragon/radspec#1]

**Comment by fulldecent** [comment]
Here is a test case input.

```solidity
pragma solidity ^0.5.0;

contract Tree {
    /// @notice Calculate the tree age in days and years
    /// @dev The total age is approximately `years` * 365 + `days`
    /// @return numYears The year part of the tree age
    /// @return numDays The day part of th tree age
    function age() external pure returns (uint256 numYears, uint numDays) {
        numYears = 10;
        numDays = 1;
    }
}
```

Could someone please proved a minimal number of lines of code I can use to install Radspec and test if that input will produce the required result?

**Comment by sohkai** [comment]
Hmm, we never actually interpret any return values...

I can see it being useful to include return variables in the `@notice` (we could probably do a `eth_call` to approximate the value), but AFAIK evaluating the call itself isn't built out.
