### ISSUE TITLE
Add some utility functions

### ISSUE THREAD

**Issue by onbjerg** [aragon/radspec#17]
I'm not entirely sure what would be cool to add, but we could possibly also support adding your own (insecure, obviously).

- `keccak256(value): bytes32`?
- `ens(name: string): address`?

Some "utility constants" could be:

- **`wei`**: 1
- `kwei`: 1000
- `ada`: 1000
- `femtoether`: 1000
- `mwei`: 1000000
- `babbage`: 1000000
- `picoether`: 1000000
- **`gwei`**: 1000000000
- `shannon`: 1000000000
- `nanoether`: 1000000000
- `nano`: 1000000000
- **`szabo`**: 1000000000000
- `microether`: 1000000000000
- `micro`: 1000000000000
- **`finney`**: 1000000000000000
- `milliether`: 1000000000000000
- `milli`: 1000000000000000
- **`ether`**: 1000000000000000000
- `kether`: 1000000000000000000000
- `grand`: 1000000000000000000000
- `einstein`: 1000000000000000000000
- `mether`: 1000000000000000000000000
- `gether`: 1000000000000000000000000000
- `tether`: 1000000000000000000000000000000

**Comment by sohkai** [comment]
Closing since we've implemented a number of "helpers" in this same vein. We can implement more as they come up :).
