### ISSUE TITLE
Add power operator (^)

### ISSUE THREAD

**Issue by onbjerg** [aragon/radspec#18]
Instead of having to write 10^18 manually (10 with 18 zeroes), it would be nice if we could just write 10^18.

**Acceptance criteria**
- Power operator using the hat character (`^`)
- Tests that demonstrate that the operator works as intended (include at least one that demonstrates its associativity)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd77fae837aa756e699775588f18cc6eff7520d5e718fb22fe5ec4c63a01aa990](https://etherscan.io/tx/0xd77fae837aa756e699775588f18cc6eff7520d5e718fb22fe5ec4c63a01aa990)

**Comment by linuxchip** [comment]
@onbjerg , i want to take this. Which file is this ?

Thanks

**Comment by onbjerg** [comment]
@linuxchip Multiple files. You will have to adjust the scanner, parser and evaluator. I think a good starting point would be to check how multiplication works in the interpreter :)

**Comment by linuxchip** [comment]
@onbjerg , thanks for the input. I will start working on this

**Comment by onbjerg** [comment]
Cool! Let me know if you have questions 😊

**Comment by linuxchip** [comment]
@onbjerg , just one quick question. 

Which interpreter you are mentioning here ?

**Comment by onbjerg** [comment]
@linuxchip The Radspec interpreter

**Comment by linuxchip** [comment]
@onbjerg , i checked aragon/radspec directory, but somehow i am not getting exactly.

I see multiplication code in parser/index.js at line 150 ( is this you are mentioning to check how multiplication works in interpreter ? )

multiplication () {
    let node = this.unary()

    while (this.matches('SLASH', 'STAR')) {
      let operator = this.previous().type
      let right = this.unary()

      node = {
        type: 'BinaryExpression',
        operator,
        left: node,
        right
      }
    }

    return node
  }


Thanks

**Comment by onbjerg** [comment]
That's the parser. It takes in tokens (in this case, for multiplication, it is the `STAR` token).

The parser takes in tokens and generates an [Abstract Syntax Tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) which is then read by the evaluator to actually perform the multiplication.

**Comment by oivoodoo** [comment]
@onbjerg could you check the transfer?

**Comment by oivoodoo** [comment]
@onbjerg it's still status ` Pending maintainer confirmation `. Could you check it?

**Comment by oivoodoo** [comment]
@onbjerg and again write you about the `pending status` :)

**Comment by luisivan** [comment]
@oivoodoo we are confirming bounties now, payout should arrive shortly

**Comment by oivoodoo** [comment]
@luisivan, it looks like I received it. in this time I setup metamask and bounty program properly.  Thank you!
