### ISSUE TITLE
Support fixed point numbers

### ISSUE THREAD

**Issue by onbjerg** [aragon/radspec#2]
We currently do not support [fixed point numbers](https://solidity.readthedocs.io/en/develop/types.html#fixed-point-numbers), but we probably should (even though I have yet to see someone use them in the wild).

**Acceptance criteria**
- The fixed point number type is added
- Test cases are added for calling a contract that returns a fixed point number
- Test cases are added performing basic arithmetic on fixed point numbers

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbaba334a50d4fea438dc2771593e9ead0b9fe98b91a4762dd2277f6d6c088ed3](https://etherscan.io/tx/0xbaba334a50d4fea438dc2771593e9ead0b9fe98b91a4762dd2277f6d6c088ed3)

**Comment by oivoodoo** [comment]
Hey @onbjerg.

Could you place example how to define fixed type?

"`a: fixed7x10`"

should it be applied on identifiers only?

Thank you!

**Comment by onbjerg** [comment]
It should be applied everywhere that types are already applied, which can also be return values of function calls

**Comment by oivoodoo** [comment]
@onbjerg have you seen https://github.com/zaach/jison ? bison, lexer for js implementation. I want to ask you why you decided to implement own scanner and parser? Lets say for location issue I believe it's part of the jison, define language spec and it would work fine. I am not 100% sure but anyway mentioned it for just in case.

**Comment by onbjerg** [comment]
@oivoodoo Yes, I have seen the various parser generators out there (like PEG.js), but the primary issue is that we want full control over what we can do and how it is done in regards to Radspec, so we have to have as little magic going on as possible :)

**Comment by rsercano** [comment]
Awesome thanks ! May I get the bounty now ? :) @bingen

**Comment by john-light** [comment]
Hi @rsercano bounty payouts are not instant, they are paid out weekly or so. Make sure you are set up properly to receive the bounty, instructions here: http://wiki.aragon.one/tutorials/Status_Open_Bounty_Guide/
