### ISSUE TITLE
Show where payments are being sent to in the Finance and Voting apps

### ISSUE THREAD

**Issue by john-light** [aragon/radspec#29]
When the user initiates a payment from the Finance app, the destination address is not shown in the signer view. This is important information that the user should be shown before confirming the payment.

![financedetail1](https://user-images.githubusercontent.com/9424721/40387575-fdcfa70e-5dc1-11e8-832a-cb044fefd88b.png)

Likewise, once the payment moves from the Finance app to the Voting app, the destination address is not shown in the Vote view. This information should be shown here as well.

![votingdetail1](https://user-images.githubusercontent.com/9424721/40387613-186ce2fc-5dc2-11e8-85bd-3121ea218bbb.png)

**Comment by ricburton** [comment]
This is so great.

Cheers,

Richard

**Comment by izqui** [comment]
Thanks! Closing here as this needs to be fixed directly in the radspec comments of the app https://github.com/aragon/aragon-apps/issues/333
