### ISSUE TITLE
Support calling methods on own contract

### ISSUE THREAD

**Issue by onbjerg** [aragon/radspec#4]
Support calling methods on the current contract instance. For example, for a contract, `Simple.sol`:

```js
contract Simple {
  string public symbol = "SMPL";

  /**
   * @notice Changes the symbol from `self.symbol()` to `_newSymbol`
   */
  function setSymbol (string _newSymbol) public {
    symbol = _newSymbol;
  }
}
```

**Acceptance criteria**
- The Radspec string in the example above works for transaction to a deployed version of the above contract that calls `setSymbol`.
- Tests, tests, tests
- The Radspec entrypoint (`src/index.js`) should not change

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbb9f9264ae474fa4d763c31bebf437527f9af7196268b36d19c9da7e04c1e83c](https://etherscan.io/tx/0xbb9f9264ae474fa4d763c31bebf437527f9af7196268b36d19c9da7e04c1e83c)

**Comment by ITNAAG** [comment]
nice

**Comment by rcullito** [comment]
@sohkai I believe you are due to receive some ANT tokens as a result of your PR here! Apologies on the delayed notification, but if you log into open bounty and update your ETH address the transaction should release the tokens from the bounty contract to your account.

**Comment by sohkai** [comment]
Thanks @rcullito, have done it now :).
