### ISSUE TITLE
Would it be possible to have some toAscii helper for bytes arguments?

### ISSUE THREAD

**Issue by ottodevs** [aragon/radspec#56]
Because `bytesX` arguments fit better than strings in some cases, I think it would be really helpful for the user to have a radspec helper that outputs the friendly ASCII or UTF8 value (as web3 utils has).

Example:
```sol
/**
 * @notice Add entity `@toAscii(_name)` with address `_addr` to the registry
 */
function addEntry(address _address, bytes32 _name) {...}
```

Those helpers would be pure functions, so they should not decrease overall safety

I can submit a PR for that if you find it is a good idea.

**Comment by izqui** [comment]
Sounds like a good idea to me! Let's make sure we support both `bytesX` and arbitrary-size `bytes`

**Comment by sembrestels** [comment]
In the latest version of web3, `toAscii` [has been deprecated](https://web3js.readthedocs.io/en/1.0/web3-utils.html#hextoascii) in favor of `hexToAscii`. And I would propose to expose `hexToUtf8(hex)` instead, as well as `hexToNumber(hex)`. Do you agree?
