### ISSUE TITLE
Documentation for use with web3

### ISSUE THREAD

**Issue by jklepatch** [aragon/radspec#75]
Any example of how to use radspec with web3?

**Comment by sohkai** [comment]
You don't have to provide a web3 instance or provider instance, but there are some options you can pass to specify how you'd like to connect: [`options.eth`](https://github.com/aragon/radspec/blob/master/src/index.js#L53) or [`options.ethNode`](https://github.com/aragon/radspec/blob/master/src/index.js#L54).

**Comment by jklepatch** [comment]
Its not that I want to give a web3 provider to radspec, but its more the other way around: I would like to keep working with web3 in my dapp, and have radspec complement web3. For example, when I execute a specific method of my smart contract on web3, I am wondering how to use radpsec in this specific context to display error messages.

**Comment by sohkai** [comment]
If you already have radspec templates for these smart contracts, e.g. as the `@notice` declarations in the contract's functions, you can feed these strings into radspec with the transaction data and radspec will hydrate the template.

Basically:

1. Dev writes radspec template, attaches it to the contract somehow (aragon uses a published artifact.json file with these templates attached to function signatures, e.g. [this one](https://ipfs.eth.aragon.network/ipfs/QmfRaZ8ysioHejiqPyQmm5N5QjE9Bm8EeiW33KP7hr9z8F/artifact.json))
2. User interacts with your app, attempts to call an on-chain method
3. App passes transaction data and radspec template string to this module
4. This module either returns with the hydrated string or an error
5. Display hydrated string

**Comment by sohkai** [comment]
Closing; the concern appears to have been addressed.
