### ISSUE TITLE
Use precision from contract if not explicitely specified for @tokenAmount

### ISSUE THREAD

**Issue by schmidsi** [aragon/radspec#77]
So that:
```
"Transfer `@tokenAmount(self, amount)` to `recipient`"`
```

returns the same as:

```
"Transfer `@tokenAmount(self, amount, true, (self.decimals(): int)` to `recipient`"
```

I'm happy to open a pull-request for this, I just want to check if this sounds meaningful to you.

**Comment by sohkai** [comment]
Hmm, I'm not sure it will look that nice; most tokens have 18 decimals and having the precision set at 18 would result in some ugly numbers in the resulting strings :/

**Comment by schmidsi** [comment]
In my tests the decimals were only displayed if that precision was actually necessary. For example:

`antContract.methods.transfer('0xfD85b83369E72512A34E23fc575b96761a11F9fD', '1000000000000000000')` 

resolved to `1 ANT` and

`antContract.methods.transfer('0xfD85b83369E72512A34E23fc575b96761a11F9fD', '1000000000000000')` 

resolved to `0.001 ANT`. Whereas with the default setting, the same transaction would resolve to `0 ANT` which is very dangerously misleading. We could have another parameter called `fixed` (or something) that sets the minimum of decimals. So that we have: `1.0000 ANT`. What do you think?

**Comment by sohkai** [comment]
Hmm yes, I can see how this would be misleading. However, I feel like this is something that we won't be able to completely fix at the radspec level, since we won't ever be able to know how many significant digits are relevant for all tokens here, but perhaps we make this behaviour less surprising.

A `fixed` mode that preserves digits could be useful, but I'm also thinking it would be good to use `~0.01 ANT` (or similar) in those cases where it would show 0. Basically, `0 + (10 ^ (-decimals))` when we would completely truncate.

**Comment by schmidsi** [comment]
I like the `~`! So here is my recommendation:

The parameter `precision` is `undefined` by default. Default behaviour is like former `precision === token.decimals`:

Value => | Display
------------ | ---:
`1000000000000000000` | `1`
`1000000000000000` | `0.001`
`1` | `0.000000000000000001`


It is a sane default, no information gets lost ever and it safes space where possible. The only problem is: If one want to compare multiple values, usually in a table with right aligned values, one might need fixed decimals. This is where this parameter comes into play: one can set a fixed amount of decimals (like [JavaScript's `toFixed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)):

__Assuming precision is set to `3`__

Value => | Display
------------ | ---:
`1000000000000000000` | `1.000`
`1000000000000000` | `0.001`
`1` | `~0.000`
`1000000000000000001` | `~1.000`

Whereas the "~" indicates that the value was rounded and some information is lost.

This would be a slightly breaking change unfortunately.

Thoughts?

**Comment by sohkai** [comment]
I really like this! I would only push for having `precision` be set with a default (2 or 3), so it's _fairly_ similar to the current behaviour, and using `-1` or `null` to signify the precision as the token's decimal range.
